version: "3"
services:
  ui:
    build: .
    image: react-starter:4.5.0
    ports:
      - 8081:8080
    volumes:
      - dist:/tmp/react-starter/dist
  nginx:
    image: nginx:1.13.3
    ports:
      - 8080:80
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  portainer:
    image: portainer/portainer:1.14.0
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  dist:
