export const ADD_TODO = 'ADD_TODO';
export type ADD_TODO = 'ADD_TODO';

export const TOGGLE_TODO = 'TOGGLE_TODO';
export type TOGGLE_TODO = 'TOGGLE_TODO';

export const FETCH_TODOS = 'FETCH_TODOS';
export type FETCH_TODOS = 'FETCH_TODOS';

export const FETCH_TODOS_PENDING = 'FETCH_TODOS_PENDING';
export type FETCH_TODOS_PENDING = 'FETCH_TODOS_PENDING';

export const FETCH_TODOS_FULFILLED = 'FETCH_TODOS_FULFILLED';
export type FETCH_TODOS_FULFILLED = 'FETCH_TODOS_FULFILLED';

export const FETCH_TODOS_REJECTED = 'FETCH_TODOS_REJECTED';
export type FETCH_TODOS_REJECTED = 'FETCH_TODOS_REJECTED';
